/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xbig_base_NativeObjectPointer */

#ifndef _Included_org_xbig_base_NativeObjectPointer
#define _Included_org_xbig_base_NativeObjectPointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xbig_base_NativeObjectPointer
 * Method:    _getObject
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_xbig_base_NativeObjectPointer__1getObject
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
