///////////////////////////////////////////////////////////////////////////////
/// This source file is generated by cpp4j
/// For the latest info, see http://www.ogre4j.org/
/// 
/// Copyright (c) 2006 OneStepAhead AG, Stuttgart. All rights reserved.
/// Also see acknowledgements in Readme.html
/// 
/// This program is free software; you can redistribute it and/or modify it under
/// the terms of the GNU Lesser General Public License as published by the Free Software
/// Foundation; either version 2 of the License, or (at your option) any later
/// version.
/// 
/// This program is distributed in the hope that it will be useful, but WITHOUT
/// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
/// FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
/// 
/// You should have received a copy of the GNU Lesser General Public License along with
/// this program; if not, write to the Free Software Foundation, Inc., 59 Temple
/// Place - Suite 330, Boston, MA 02111-1307, USA, or go to
/// http://www.gnu.org/copyleft/lesser.txt.
///
/// Machine generated file
///
/// Author: Frank Bielig
///
///////////////////////////////////////////////////////////////////////////////


#ifndef _Included_jni_base_
#define _Included_jni_base_

#include <jni.h>
#include <string>


#ifdef WIN32
	#define EXPORT __declspec(dllexport)
#else
	#define EXPORT
#endif


namespace org { namespace xbig { namespace jni {
	
EXPORT std::string to_stdstring(JNIEnv* env, jstring jString);

EXPORT std::wstring to_stdwstring(JNIEnv* env, jstring jString);

EXPORT char* to_cstring(JNIEnv* env, jstring jString);

EXPORT jstring to_jstring(JNIEnv* env, const std::string& str);

EXPORT jstring to_jstring(JNIEnv* env, const char*);

EXPORT jstring to_jstring(JNIEnv* env, const std::wstring&);

}}}

#ifdef __cplusplus
extern "C" {
#endif




#ifdef __cplusplus
}
#endif
#endif
